# Generated by Django 3.1.5 on 2021-01-11 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210111_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publicado',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='conteudo',
            new_name='conteudos',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 20, 11, 8, 191727, tzinfo=utc)),
        ),
    ]
